# -*- coding: utf-8 -*-
"""2702259986 - Theophilus Alexander Elvan - Session 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mnnNIRkYplAbioOYBCE1aZuD_BAFC8DL
"""

x = 1
x

x = x + 1
x

x = 1
y = x + 1
x = 2
y

"""#Import numpy"""

import numpy as np

x = np.array([1, 4, 3])
x

y = np.array([[1, 4, 3],[9, 2, 7]])
y

def my_adder(a, b, c):
  """
  function to sum the 3 numbers
  input: 3 number a, b, c
  output: the sum of a, b, c
  outhor: Theophilus
  date:
  """

  #this is the sumination
  out = a + b + c

  return out

my_adder(1,2,3)

def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
    status ='off'
  return status

status = my_thermo_stat(65,75)
print(status)

status = my_thermo_stat(75,65)
print(status)

status = my_thermo_stat(65,63)
print(status)