# -*- coding: utf-8 -*-
"""2702259986-Theophilus-Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HITSr1EG6273xKUhhfg9ZnDliYtBOzcb
"""

import numpy as np
import matplotlib.pyplot as plt

x =  [0, 1, 2, 3]
y =  [0, 1, 4, 9]
plt.plot(x, y)
plt.show

import matplotlib.pyplot as plt

import pandas as pd

ts = pd.Series(np.random.randn(1000), index = pd.date_range("1/1/2000", periods=1000))
ts = ts.cumsum()
ts.plot();

df = pd.DataFrame(np.random.randn(1000, 4),index = ts.index, columns = list("ABCD"))
df = df.cumsum()
plt.figure();
df.plot();
#<Figure size 432x288 with 0 Axes>